image: maven:4.0.0

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/  

stages:
  - build
  - test
  - deploy


before_script:
  - chmod +x mvnw

teste:
    stage: test
    #script : ./mvnw test
    script: -eco "teste pass" 

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/destiny-0.0.1-SNAPSHOT.jar 

production:
    stage: deploy
    script: 
        - echo "Deploy sucess"
    only: 
        - main
