image: maven:latest

stages:
  - build
  - test
  - deploy


variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/  


build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/destiny-0.0.1-SNAPSHOT.jar

teste:
    stage: test
    #script : ./mvnw test
    script:
        - echo 'teste pass'

production:
    stage: deploy
    script:
      - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" > deploy_key.pem
      - chmod 600 deploy_key.pem
      - scp -i deploy_key.pem -o StrictHostKeyChecking=no target/destiny-0.0.1-SNAPSHOT.jar ubuntu@3.17.198.197:/opt/destiny/
      - rm -f deploy_key.pem
      - echo "Deploy sucess"
    only: 
        - main
